### ISSUE TITLE
Support for PSBM

### ISSUE THREAD

**Issue by bastelfreak** [dj-wasabi/puppet-zabbix#123]
Hi,
I would like to add support for Parallels Server Bare Metal. This is a centos 6 fork, but is doesn't provide the operatingsystemrelease fact:

```
# facter -p os osfamily operatingsystem operatingsystemrelease
operatingsystem => PSBM
operatingsystemrelease => nil
os => {"name"=>"PSBM", "family"=>"RedHat"}
osfamily => RedHat
```

to check if $::operatingsystemrelease is nil in the repo.pp is very dirty, do you have any recommendations?

**Comment by dj-wasabi** [comment]
Hi @bastelfreak 

Well, maybe now is the time to change repo.pp and use the osfamily fact instead of operatingsystemrelease in the case statement. This will help you for the PSBM (Never heard of that one though ;-)) and is more future proof for other clones with exists in outer (web)space.

I'm not sure if I can change this in the next weeks,  but I'll try.

Kind regards,
Werner

**Comment by dj-wasabi** [comment]
An PR is already created and merged. Issue will be closed.
